// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { DB_URI } from "./config/env.ts";
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: DB_URI!
  }
});
